name: Run Migrations

on:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add server to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 192.250.239.80 >> ~/.ssh/known_hosts

    - name: Run migrations on cPanel server
      run: |
        ssh telkomae@192.250.239.80 "cd /home/telkomae/public_html/dev-dashboard && php artisan migrate --force"
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: hashtag_smP+]3MTCZN3xU
        DB_USERNAME: hashtag_production_user
        DB_PASSWORD: f0^fdFvIEy37